name: chat_component
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.6
  get_it: ^7.3.0

  image_picker: ^1.0.7

  permission_handler: ^11.1.0

  intl: ^0.17.0

  flash: ^2.0.3

  camerawesome: ^2.0.0+1

  lottie: ^2.7.0

  firebase_messaging: ^14.7.8
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6


  cached_network_image: ^3.3.1


  awesome_notifications: ^0.7.4+1

  easy_debounce: ^2.0.3


  agora_rtc_engine: ^6.2.6

  http: ^0.13.5

  path_provider: ^2.1.1
  file_picker: ^6.1.1

  just_audio: ^0.9.36
  audio_session: ^0.1.19
  rxdart: ^0.27.7

  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  open_filex: ^4.4.0

  media_scanner: ^2.1.0

  photo_gallery: ^2.2.1

  transparent_image: ^2.0.1

  camera: ^0.11.0+1
  mime_type: ^1.0.0


  loading_animation_widget: ^1.2.1

  image_cropper: ^3.0.1
  image_painter: ^0.7.1

  audio_waveforms: ^1.0.5
  audio_wave_url_package: ^1.0.34

  video_player: ^2.8.6
  chewie: ^1.8.1
  video_thumbnail: ^0.5.3

  socket_io_client: ^2.0.3+1

  #networking
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  pretty_dio_logger: ^1.1.1

  #retrofit
  retrofit: ^3.3.1
  freezed_annotation: ^2.2.0
  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'
  freezed: ^2.2.0
  build_runner: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - lib/chat_assets/images/icons/
    - lib/chat_assets/images/gif/
    - lib/chat_assets/images/image/
    - lib/chat_assets/images/logo/
    - lib/chat_assets/lottie/
    - lib/chat_assets/sounds/


  fonts:
    - family: 'Inter'
      fonts:
        - asset: lib/chat_assets/fonts/Inter-Black.otf
        - asset: lib/chat_assets/fonts/Inter-Bold.otf
        - asset: lib/chat_assets/fonts/Inter-ExtraBold.otf
        - asset: lib/chat_assets/fonts/Inter-ExtraLight.otf
        - asset: lib/chat_assets/fonts/Inter-Light.otf
        - asset: lib/chat_assets/fonts/Inter-Medium.otf
        - asset: lib/chat_assets/fonts/Inter-Regular.otf
        - asset: lib/chat_assets/fonts/Inter-SemiBold.otf
        - asset: lib/chat_assets/fonts/Inter-Thin.otf


  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
